---
title: "StatsForecast's Models"
---


## Automatic Forecasting
Automatic forecasting tools search for the best parameters and select the best possible model for a series of time series. These tools are useful for large collections of univariate time series.

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`AutoARIMA`](../../models#class-autoarima)|✅|✅|✅|✅|✅|
|[`AutoETS`](../../models#class-autoets)|✅|✅|✅|✅|✅|
|[`AutoCES`](../../models#class-autoces)|✅|✅|✅|✅||
|[`AutoTheta`](../../models#class-autotheta)|✅|✅|✅|✅|✅|


## ARIMA Family
These models exploit the existing autocorrelations in the time series.

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`ARIMA`](../../models#class-arima)|✅|✅|✅|✅|✅|
|[`AutoRegressive`](../../models#class-autoregressive)|✅|✅|✅|✅|✅|


## Theta Family
Fit two theta lines to a deseasonalized time series, using different techniques to obtain and combine the two theta lines to produce the final forecasts.

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`Theta`](../../models#class-theta)|✅|✅|✅|✅|✅|
|[`OptimizedTheta`](../../models#class-optimizedtheta)|✅|✅|✅|✅|✅|
|[`DynamicTheta`](../../models#class-dynamictheta)|✅|✅|✅|✅|✅|
|[`DynamicOptimizedTheta`](../../models#class-dynamicoptimizedtheta)|✅|✅|✅|✅|✅|


## Multiple Seasonalities
Suited for signals with more than one clear seasonality. Useful for low-frequency data like electricity and logs.

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`MSTL`](../../models#class-mstl)|✅|✅|✅|✅|✅|


## GARCH and ARCH Models
Suited for modeling time series that exhibit non-constant volatility over time. The ARCH model is a particular case of GARCH. 

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`GARCH`](../../models#class-garch)|✅|✅|✅|✅|✅|
|[`ARCH`](../../models#class-arch)|✅|✅|✅|✅|✅|


## Baseline Models
Classical models for establishing baseline.

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`HistoricAverage`](../../models#class-historicaverage)|✅|✅|✅|✅|✅|
|[`Naive`](../../models#class-naive)|✅|✅|✅|✅|✅|
|[`RandomWalkWithDrift`](../../models#class-randomwalkwithdrift)|✅|✅|✅|✅|✅|
|[`SeasonalNaive`](../../models#class-seasonalnaive)|✅|✅|✅|✅|✅|
|[`WindowAverage`](../../models#class-windowaverage)|✅|||||
|[`SeasonalWindowAverage`](../../models#class-seasonalwindowaverage)|✅|||||


## Exponential Smoothing
Uses a weighted average of all past observations where the weights decrease exponentially into the past. Suitable for data with clear trend and/or seasonality. Use the `SimpleExponential` family for data with no clear trend or seasonality.

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`SimpleExponentialSmoothing`](../../models#class-simpleexponentialsmoothing)|✅|||||
|[`SimpleExponentialSmoothingOptimized`](../../models#class-simpleexponentialsmoothingoptimized)|✅|||||
|[`Holt`](../../models#class-holt)|✅|✅|✅|✅|✅|
|[`HoltWinters`](../../models#class-holtwinters)|✅|✅|✅|✅|✅|


## Sparse or Intermittent 
Suited for series with very few non-zero observations

|Model | Point Forecast | Probabilistic Forecast | Insample fitted values | Probabilistic fitted values |
|:------|:-------------:|:----------------------:|:---------------------:|:----------------------------:|
|[`ADIDA`](../../models#class-adida)|✅|||||
|[`CrostonClassic`](../../models#class-crostonclassic)|✅|||||
|[`CrostonOptimized`](../../models#class-crostonoptimized)|✅|||||
|[`CrostonSBA`](../../models#class-crostonsba)|✅|||||
|[`IMAPA`](../../models#class-imapa)|✅|||||
|[`TSB`](../../models#class-tsb)|✅|||||



