-- function Reader(input)
--     return pandoc.Pandoc(input:map(        
--         function (s) 
--             -- print(s)
--             return pandoc.CodeBlock(s.text) 
--         end
--     ))
--   end