name: Bug report
title: "[<Library component: Model|Core|etc...>] "
description: Problems and issues with code of the library
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the problem..
        Please make sure what you are reporting is a bug with reproducible steps. To ask questions
        or share ideas, please post on our [Slack community](https://join.slack.com/t/nixtlacommunity/shared_invite/zt-1h77esh5y-iL1m8N0F7qV1HmH~0KYeAQ) instead.

  - type: textarea
    attributes:
      label: What happened + What you expected to happen
      description: Describe 1. the bug 2. expected behavior 3. useful information (e.g., logs)
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened. Further,
        please also explain why you think the behaviour is erroneous. It is extremely helpful if you can
        copy and paste the fragment of logs showing the exact error messages or wrong behaviour here.

        **NOTE**: please copy and paste texts instead of taking screenshots of them for easy future search.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions / Dependencies
      description: Please specify the versions of the library, Python, OS, and other libraries that are used.
      value: |
        <details><summary>Click to expand</summary>
        Dependencies:

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible example
      description: >
        Please provide a reproducible script. Providing a simple way to reproduce the issue
        (minimal / no external dependencies) will help us triage and address issues in the timely manner!
      value: |
        ```python
        # paste your code here
        ```
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Issue Severity
      description: |
        How does this issue affect your experience as user?
      multiple: false
      options:
        - "Low: It annoys or frustrates me."
        - "Medium: It is a significant difficulty but I can work around it."
        - "High: It blocks me from completing my task."
    validations:
      required: false
