name: Upload Python Package to PyPI

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels for cp${{ matrix.python-version }}-${{ matrix.os-platform[1] }}
    runs-on: ${{ matrix.os-platform[0] }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [310, 311, 312, 313]
        os-platform:
          [
            [ubuntu-latest, manylinux_x86_64],
            [ubuntu-latest, manylinux_aarch64],
            [windows-latest, win_amd64],
            [macos-13, macosx_x86_64],
            [macos-14, macosx_arm64],
          ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "true"

      - name: Set up QEMU
        if: matrix.os-platform[1] == 'manylinux_aarch64'
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@ee02a1537ce3071a004a6b08c41e72f0fdc42d9a # v3.4.0
        env:
          CIBW_BUILD: cp${{ matrix.python-version }}-${{ matrix.os-platform[1] }}

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: artifact-cp${{ matrix.python-version }}-${{ matrix.os-platform[1] }}
          path: wheelhouse/*.whl
          retention-days: 1

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "true"

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"

      - name: Build sdist
        run: |
          python -m pip install build
          python -m build --sdist --outdir dist

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: dist/*.tar.gz

  upload:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
